name: trans
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.19.0
  http: ^1.1.0
  geolocator: ^13.0.0
  geolocator_linux: ^0.2.1
  cupertino_icons: ^1.0.2

  vibration: ^3.1.0 
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2

  shared_preferences: ^2.2.0
  path_provider: ^2.1.5

  supabase_flutter: ^2.0.0
  image_picker: ^1.0.7
  flutter_dotenv: ^6.0.0
  
  # UPDATED VERSION
  dynamic_color: ^1.6.0
  emoji_picker_flutter: ^4.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
 # NEW: For Private Chat Encryption
  encrypt: ^5.0.3
  crypto: ^3.0.7
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.2.0
  package_info_plus: ^8.0.0
  uuid: ^4.2.2

  # Ticket Logic
  google_mlkit_barcode_scanning: ^0.13.0
  image_cropper: ^8.0.0
  image: ^4.2.0
  # Linux/Desktop Support
  zxing_lib: ^1.1.4
  crop_your_image: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  peanut: ^5.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#ffffff"
    theme_color: "#0175C2"
  macos:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
  linux:
    generate: true
    image_path: "assets/icon.png"
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/assets/
    - .env
    - lib/assets/logo.png